spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystems?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create